name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2] # Usa 2 instâncias paralelas

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # Ou a versão do Node.js que você está usando

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: npm start &
        env:
          PORT: 3000 # Ajuste se necessário para o seu ambiente

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3000 --timeout=300000 --retry=10
        timeout-minutes: 60

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
